import type { Response } from "express";
import { Router } from "express";
import { prisma } from "../lib/prisma";
import { asyncHandler } from "../lib/asyncHandler";
import { requireAuth, requireRole } from "../middleware/auth";
import { renderPdf } from "../lib/pdf";
import { renderXlsx, XLSX_CONTENT_TYPE } from "../lib/excel";

export const reportsRouter = Router();
reportsRouter.use(requireAuth, requireRole("Admin", "Accountant"));

interface ReportData {
  title: string;
  subtitle?: string;
  headers: string[];
  rows: Array<Array<string | number>>;
  summaryLines?: Array<[string, string]>;
}

// Emit a report as PDF (default) or XLSX (?format=xlsx). `pdfOnly` forces PDF.
async function send(res: Response, format: unknown, d: ReportData, pdfOnly = false): Promise<void> {
  const wantXlsx = !pdfOnly && String(format).toLowerCase() === "xlsx";
  const slug = d.title.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  if (wantXlsx) {
    const buf = await renderXlsx({
      sheetName: d.title.slice(0, 31),
      title: d.subtitle ? `${d.title} — ${d.subtitle}` : d.title,
      headers: d.headers,
      rows: d.rows,
    });
    res.setHeader("Content-Type", XLSX_CONTENT_TYPE);
    res.setHeader("Content-Disposition", `attachment; filename="${slug}.xlsx"`);
    res.end(buf);
    return;
  }
  const pdf = renderPdf({
    title: d.title,
    subtitle: d.subtitle,
    lines: d.summaryLines,
    table: { headers: d.headers, rows: d.rows },
    footer: "Generated by Makthab",
  });
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `inline; filename="${slug}.pdf"`);
  res.end(pdf);
}

const monthWindow = (month: number, year: number) => ({
  gte: new Date(year, month - 1, 1),
  lt: new Date(year, month, 1),
});

// GET /reports/fee-collection?month&year
reportsRouter.get(
  "/fee-collection",
  asyncHandler(async (req, res) => {
    const month = Number(req.query.month);
    const year = Number(req.query.year);
    const fees = await prisma.feePayment.findMany({
      where: { feeMonth: month, feeYear: year },
      include: { student: true },
      orderBy: { id: "asc" },
    });
    const total = fees.reduce((s, f) => s + f.amountPaid, 0);
    await send(res, req.query.format, {
      title: "Fee Collection Report",
      subtitle: `${month}/${year}`,
      headers: ["Receipt", "Student", "Type", "Paid", "Method", "Date"],
      rows: fees.map((f) => [
        f.receiptNo,
        f.student?.fullName ?? "-",
        f.feeType,
        f.amountPaid.toFixed(2),
        f.paymentMethod,
        new Date(f.paymentDate).toISOString().slice(0, 10),
      ]),
      summaryLines: [["Total Collected", total.toFixed(2)], ["Payments", String(fees.length)]],
    });
  })
);

// GET /reports/defaulters?month&year
reportsRouter.get(
  "/defaulters",
  asyncHandler(async (req, res) => {
    const month = Number(req.query.month);
    const year = Number(req.query.year);
    const students = await prisma.student.findMany({ where: { status: "active" }, include: { class: true } });
    const paid = await prisma.feePayment.findMany({
      where: { feeType: "monthly", feeMonth: month, feeYear: year },
      select: { studentId: true },
    });
    const paidSet = new Set(paid.map((p) => p.studentId));
    const defaulters = students.filter((s) => !paidSet.has(s.id));
    await send(res, req.query.format, {
      title: "Defaulters Report",
      subtitle: `${month}/${year}`,
      headers: ["Admission", "Student", "Class", "WhatsApp"],
      rows: defaulters.map((s) => [s.admissionNo, s.fullName, s.class?.name ?? "-", s.whatsappNo]),
      summaryLines: [["Total Defaulters", String(defaulters.length)]],
    });
  })
);

// GET /reports/attendance?class_id&month&year
reportsRouter.get(
  "/attendance",
  asyncHandler(async (req, res) => {
    const classId = req.query.class_id ? Number(req.query.class_id) : undefined;
    const month = Number(req.query.month);
    const year = Number(req.query.year);
    const rows = await prisma.attendance.findMany({
      where: {
        date: monthWindow(month, year),
        ...(classId ? { student: { classId } } : {}),
      },
      include: { student: true },
    });
    const byStudent = new Map<number, { name: string; present: number; total: number }>();
    for (const r of rows) {
      const cur = byStudent.get(r.studentId) ?? { name: r.student?.fullName ?? "", present: 0, total: 0 };
      cur.total += 1;
      if (r.status === "present" || r.status === "late") cur.present += 1;
      byStudent.set(r.studentId, cur);
    }
    await send(res, req.query.format, {
      title: "Attendance Report",
      subtitle: `${month}/${year}${classId ? ` — class ${classId}` : ""}`,
      headers: ["Student", "Present", "Total", "%"],
      rows: [...byStudent.values()].map((v) => [
        v.name,
        v.present,
        v.total,
        v.total ? Math.round((v.present / v.total) * 100) : 0,
      ]),
    });
  })
);

// GET /reports/expenses?period
reportsRouter.get(
  "/expenses",
  asyncHandler(async (req, res) => {
    const period = req.query.period ? Number(req.query.period) : new Date().getFullYear();
    const expenses = await prisma.expense.findMany({
      where: { expenseDate: { gte: new Date(period, 0, 1), lt: new Date(period + 1, 0, 1) } },
      include: { category: true },
      orderBy: { expenseDate: "asc" },
    });
    const total = expenses.reduce((s, e) => s + e.amount, 0);
    await send(res, req.query.format, {
      title: "Expense Report",
      subtitle: String(period),
      headers: ["Voucher", "Category", "Payee", "Amount", "Date"],
      rows: expenses.map((e) => [
        e.voucherNo,
        e.category?.name ?? "-",
        e.payee,
        e.amount.toFixed(2),
        new Date(e.expenseDate).toISOString().slice(0, 10),
      ]),
      summaryLines: [["Total Expenses", total.toFixed(2)]],
    });
  })
);

// GET /reports/salary-register?month&year
reportsRouter.get(
  "/salary-register",
  asyncHandler(async (req, res) => {
    const month = Number(req.query.month);
    const year = Number(req.query.year);
    const salaries = await prisma.salaryPayment.findMany({
      where: { salaryMonth: month, salaryYear: year },
      include: { staff: true },
      orderBy: { id: "asc" },
    });
    const total = salaries.reduce((s, p) => s + p.netAmount, 0);
    await send(res, req.query.format, {
      title: "Salary Register",
      subtitle: `${month}/${year}`,
      headers: ["Staff", "Gross", "Deductions", "Net", "Date"],
      rows: salaries.map((p) => [
        p.staff?.fullName ?? "-",
        p.grossAmount.toFixed(2),
        p.deductions.toFixed(2),
        p.netAmount.toFixed(2),
        new Date(p.paymentDate).toISOString().slice(0, 10),
      ]),
      summaryLines: [["Total Net Payout", total.toFixed(2)]],
    });
  })
);

// GET /reports/financial-summary?year — PDF only.
reportsRouter.get(
  "/financial-summary",
  asyncHandler(async (req, res) => {
    const year = Number(req.query.year) || new Date().getFullYear();
    const window = { gte: new Date(year, 0, 1), lt: new Date(year + 1, 0, 1) };
    const [feeAgg, expenseAgg, salaryAgg] = await Promise.all([
      prisma.feePayment.aggregate({ _sum: { amountPaid: true }, where: { paymentDate: window } }),
      prisma.expense.aggregate({ _sum: { amount: true }, where: { expenseDate: window } }),
      prisma.salaryPayment.aggregate({ _sum: { netAmount: true }, where: { paymentDate: window } }),
    ]);
    const income = feeAgg._sum.amountPaid ?? 0;
    const expenses = expenseAgg._sum.amount ?? 0;
    const salaries = salaryAgg._sum.netAmount ?? 0;
    await send(
      res,
      "pdf",
      {
        title: "Financial Summary",
        subtitle: String(year),
        headers: ["Line Item", "Amount"],
        rows: [
          ["Fee Income", income.toFixed(2)],
          ["Expenses", expenses.toFixed(2)],
          ["Salaries", salaries.toFixed(2)],
          ["Net Balance", (income - expenses - salaries).toFixed(2)],
        ],
      },
      true
    );
  })
);
